version: '3'
services:
  fastapi:
    image: isan19973788/fastapi
    # build:
    #   dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    # volumes:
    #   - ./app:/app
    # expose:
    #   - "8000"
    ports:
      - "8000:8000"
    networks:
      - test1

  apache:
    image: httpd:latest
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "83:83"
    # restart: always
    depends_on:
      - fastapi
    networks:
      - test1

networks:
  test1:
    driver: bridge